env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  {
    react/function-component-definition: [2, { 'namedComponents': 'arrow-function' }],
    import/order:
      [
        2,
        {
          groups: ['external', 'builtin', 'index', 'sibling', 'parent', 'internal', 'type'],
          alphabetize: { 'order': 'asc', 'caseInsensitive': true },
          newlines-between: 'always-and-inside-groups',
        },
      ],
    import/prefer-default-export: 'off',
    react/require-default-props: [2, { functions: 'defaultArguments' }],
  }
